"""
Render the paper's Type-I error table (content/figures/type1_error_table.tex)
from the simulation CSV produced by studies/type_i_error_heatmap.py.

The Overleaf file was originally hand-typed; this script regenerates the same
LaTeX layout from outputs/csvs/type_i_error_results.csv so the values stay
in sync with the simulation. Output is written to
outputs/tables/type1_error_table.tex.

Usage
-----
    python make_type1_table.py
    python make_type1_table.py --csv path/to/type_i_error_results.csv \
                               --out path/to/output.tex
"""

import argparse
from pathlib import Path

import pandas as pd


# Column ordering inside the table (matches the Overleaf file).
TEST_STATS_ORDERED = ["pooled", "max-linear", "max-log"]
TEST_STAT_HEADERS  = {
    "pooled":     "Pooled",
    "max-linear": "Max (Linear)",
    "max-log":    "Max (Log)",
}


def _fmt(value: float) -> str:
    """Format a probability as '.048' (no leading zero, 3 decimals)."""
    s = f"{value:.3f}"
    return s[1:] if s.startswith("0") else s


def render_table(rates: pd.DataFrame,
                 k_values: list[int],
                 T_values: list[int]) -> str:
    """Render the 3-block grid as a LaTeX string matching the Overleaf file."""
    n_T = len(T_values)
    col_spec = "cc|" + "|".join(["c" * n_T] * len(TEST_STATS_ORDERED))

    lines = [
        "% Type I Error Control Table",
        "% Generated by reproduction/make_type1_table.py from",
        "% outputs/csvs/type_i_error_results.csv",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\begin{{tabular}}{{{col_spec}}}",
        "",
    ]

    # Block headers row
    block_headers = []
    for i, ts in enumerate(TEST_STATS_ORDERED):
        sep = "|" if i < len(TEST_STATS_ORDERED) - 1 else ""
        block_headers.append(f"\\multicolumn{{{n_T}}}{{c{sep}}}{{{TEST_STAT_HEADERS[ts]}}}")
    lines.append("& & " + " & ".join(block_headers) + " \\\\")
    lines.append("\\midrule \\midrule")

    # T-values row (repeated per block)
    T_cells = " & ".join(str(T) for T in T_values)
    lines.append("& $T$ & " + " & ".join([T_cells] * len(TEST_STATS_ORDERED)) + " \\\\")
    lines.append("\\midrule")

    # Left-edge k label spanning all data rows
    lines.append(
        f"\\parbox[t]{{2mm}}{{\\multirow{{{len(k_values)}}}{{*}}"
        f"{{\\rotatebox[origin=c]{{90}}{{$k$}}}}}}"
    )

    # Data rows
    pivot = rates.set_index(["test_statistic", "k", "T"])["rate"]
    for k in k_values:
        cells_per_block = []
        for ts in TEST_STATS_ORDERED:
            cells_per_block.append(
                " & ".join(_fmt(pivot.loc[(ts, k, T)]) for T in T_values)
            )
        lines.append(f"& {k:<2} & " + " & ".join(cells_per_block) + " \\\\")

    lines += [
        "",
        "\\end{tabular}",
        "\\caption{\\small\\label{tab:type1}Empirical type~I error rates under "
        "the null hypothesis ($\\mu_g = 0$ for all $g$) at nominal level "
        "$\\alpha = 0.05$. Results are shown for the pooled statistic and both "
        "max statistics (linear and log boundaries) across varying numbers of "
        "arms ($k$) and sample sizes ($T$). The max-statistic tests use the "
        "qualification rule $q_0 = \\max(25, T/k)$, equivalently "
        "$\\zeta = \\max(1, 25k/T)$, which keeps qualifying arms in the regime "
        "where the Studentized statistic is close to its standard-normal limit. }",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    pkg_root = Path(__file__).parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--csv",
        type=Path,
        default=pkg_root / "outputs" / "csvs" / "type_i_error_results.csv",
        help="Path to type_i_error_results.csv",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=pkg_root / "outputs" / "tables" / "type1_error_table.tex",
        help="Where to write the rendered .tex file",
    )
    args = parser.parse_args()

    df = pd.read_csv(args.csv)
    rates = (
        df.groupby(["test_statistic", "k", "T"])["reject"]
          .mean()
          .reset_index(name="rate")
    )

    # Use whatever k and T values appear in the CSV, sorted ascending —
    # the paper grid is k in {5,10,20,50} and T in {200,500,1000,2000}.
    k_values = sorted(rates["k"].unique())
    T_values = sorted(rates["T"].unique())

    missing = [
        (ts, k, T)
        for ts in TEST_STATS_ORDERED
        for k in k_values
        for T in T_values
        if not ((rates["test_statistic"] == ts)
                & (rates["k"] == k)
                & (rates["T"] == T)).any()
    ]
    if missing:
        raise ValueError(
            f"CSV is missing cells: {missing[:5]}{'...' if len(missing) > 5 else ''}"
        )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_table(rates, k_values, T_values))
    print(f"Wrote: {args.out}")


if __name__ == "__main__":
    main()
